build:
entrypoint: main.py
environment-file: environment.yml
registered-model: titanic-best-models
scheduling:
  parameters:
    image: "root/live-demo"
    volumes:
      - "/NAS_PRD_Data_Landing_Zone/data/live-demo-project/data"
	 
trigger:
  time-event: "Dal lunedì al venerdì alle 9.00 di mattina"
